config/routes.rb
Rails.application.routes.draw do

  root 'restaurants#index'

  resources :users, only: [:new, :create, :show]
  resources :restaurants do
      resources :reservations
      resources :reviews, only: [:new, :create, :destroy]
  end
  resources :sessions, only: [:new, :create, :destroy]

end

app/models/owner.rb
class Owner < ActiveRecord::Base

  belongs_to :user
  has_many :restaurants

end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  belongs_to :restaurant
  belongs_to :user

  # validate :seats_taken
  #validates_inclusion_of :size, in: 0..100
  # validates size, :inclusion => { :in => r, :min => 1, :max => 10} }
  # lambda { |foo| foo.allowed_types }
  #validates_inclusion_of :size, in: lambda { |reservation| 1..reservation.restaurant.capacity }
  validates :time, :size, presence: true
  validate :restaurant_has_space

  def restaurant_has_space
    if self.size.between?(1,restaurant.seats_remaining(time))
    else
      errors.add(:size, "There is not enough space in the restaurant.")
    end
  end


# def seats_taken
#   var = @reservations.select{|element| element[:restaurant_id] == params[:restaurant_id] && element[:time] == params[:time]}
#   var.map(&:size).reduce(:+)
# end


# def  seats_taken
#   if size > 10
#     errors.add(:size)
#   end
# end

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  has_many :reservations
  has_many :users, through: :reservations
  belongs_to :owner, class_name: "User", foreign_key: :user_id

  has_many :reviews
  has_many :users, through: :reviews

  validates :name, :address, :phone, :capacity, presence: true
  geocoded_by :address
  after_validation :geocode

  def seats_remaining(time)
    100 - reservations.where(time: time).sum(:size)
  end

  def display_distance_to(other_restaurant)
    self.distance_to(other_restaurant, :km).round(3)
  end

end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :restaurant

  validates :comment, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :reservations
  has_many :reserved_restaurants, through: :reservations, source: :restaurant

  has_many :owned_restaurants, class_name: "Restaurant"

  has_many :reviews
  has_many :reviewed_restaunrants, through: :reviews, source: :restaurant

  has_secure_password

  validates :name, :email, :password, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

  def ensure_logged_in
    unless current_user
      flash[:alert] = "Please log in!"
      redirect_to new_session_path
    end
  end

end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController
  def new
    @owner = Owner.new
  end

  def show
    @owner = Owner.find(params[:id])
  end

  def edit
  end

  def create
    @owner = Owner.new(owner_params)
    if @owner.save
      redirect_to restaurants_url, notice: "Signed Up!"
    else
      render "new"
    end
  end

  def destroy
    @owner = Owner.find(params[:id])
  end

  def update
    @owner = Owner.find(params[:id])
    if @owner.update_attributes(owner_params)
      flash[:notice] = "Your information has been updated."
      redirect_to restaurants_url
    else
      flash[:alert] = "Your information was not updated."
      render :edit
    end
  end

  private
    def user_params
      params.require(:owner).permit(:restaurant_name, :name, :phone, :email, :password, :password_confirmation)
    end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
before_action :ensure_logged_in, only: [:destroy, :create, :update]
before_action :load_restaurant
before_action :find_reservation, only: [:show, :edit, :update, :destroy]

def show
end

def destroy
  @reservation.destroy
  redirect_to restaurant_path(@reservation.restaurant_id)
end

def edit
end

def create
  @reservation = @restaurant.reservations.build(reservation_params)
  @reservation.user = current_user
  if @reservation.save
    flash[:notice] = "Reservation was successfully created."
    redirect_to restaurant_path(@restaurant.id)
  else
    flash[:alert] = "Reservation was not successfully created."
    render 'restaurants/show'
  end
end


def update
  if @reservation.update_attributes(reservation_params)
    flash[:notice] = "The reservation has been updated."
    redirect_to user_path
  else
    flash[:alert] = "The reservation was not updated successfully"
    render :edit
  end
end

private
def reservation_params
  params.require(:reservation).permit(:time, :size, :restaurant_id, :user_id)
end

def load_restaurant
  @restaurant = Restaurant.find(params[:restaurant_id])
end

def find_reservation
  @reservation = Reservation.find(params[:id])
end

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  def index
    @restaurants = Restaurant.all
  end


    def show
      @restaurant = Restaurant.find(params[:id])
      @reservation = @restaurant.reservations.build
      @review = @restaurant.reviews.build
      @nearby_restaurants = @restaurant.nearbys
    end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.owner = current_user
    if @restaurant.save
      flash[:notice] = "Restaurant was successfully created."
      redirect_to restaurants_path
    else
      flash[:alert] = "Restaurant was not created."
      render :new
    end
  end

  def edit
    @restaurant  = Restaurant.find(params[:id])
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    if @restaurant.update_attributes(restaurant_params)
      flash[:notice] = "Restaurant was successfully updated."
      redirect_to restaurant_path(@restaurant)
    else
      flash[:alert] = "Restaurant not successfully updated."
      render :edit
    end
  end


  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy
    redirect_to restaurants_path
  end

  private
  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone, :capacity, :user_id)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :ensure_logged_in, only: [:destroy, :create, :update]
  before_action :load_restaurant
  before_action :find_reservation, only: [:show, :edit, :update, :destroy]


  def new
    @review = Review.new
  end

  def create
    @review = @restaurant.reviews.build(review_params)
    @review.user = current_user
    if @review.save
      flash[:notice] = "Review was successfully created."
      redirect_to restaurant_path(@restaurant.id)
    else
      flash[:alert] = "Review was not created."
      redirect_to restaurant_path(@restaurant.id)
    end
  end



  def destroy
  end

  private

  def review_params
    params.require(:review).permit(:comment)
  end

  def load_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def find_review
    @reservation = Reservation.find(params[:id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  layout "login_page"
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to restaurants_url, notice: "Login successful!"
    else
      flash.now[:alert] = "Invalid email or password"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to restaurants_url notice: "logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout "login_page"
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to restaurants_url, notice: "Signed up!"
    else
      render "new"
    end
  end

  def show
    @user = User.find(current_user.id)
  end

private
  def user_params
    params.require(:user).permit(:name, :phone, :email, :password, :password_confirmation)
  end


end

app/helpers/owners_helper.rb
module OwnersHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Seatyourself</title>

    <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<header>
<nav class="nav-bar">
  <h1 class='logo'><%= link_to "SeatYourself", root_path, class: 'logotext'%></h1>
  <ul class = 'nav-list'>
  <% if current_user %>
    <li><%= link_to "Log Out", session_path("current"), method: :delete  , class: "nav_link"%></li>
    <li><%= link_to "View Profile", user_path(current_user.id), class: "nav_link" %></li>
  <% else %>
    <li><%= link_to "Sign Up", new_user_path , class: "nav_link"%></li>
    <li><%= link_to "Log In", new_session_path , class: "nav_link"%></li>
  <% end %>
  </ul>
</nav>

</header>

<%if flash[:notice]%>
<p id="notice"><%= flash[:notice] %></p>
<% end %>

<% if flash[:alert]%>
<p id="alert"><%= flash[:alert] %></p>
<% end %>

<%= yield %>


</body>
</html>

app/views/layouts/login_page.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Seatyourself</title>

    <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <h1 class="logo"><%= link_to "SeatYourself", root_path, class: 'logotext'%></h1>
  </header>

<%= yield %>



</body>
</html>

app/views/owners/create.html.erb
<h1>Owners#create</h1>
<p>Find me in app/views/owners/create.html.erb</p>

app/views/owners/destroy.html.erb
<h1>Owners#destroy</h1>
<p>Find me in app/views/owners/destroy.html.erb</p>

app/views/owners/new.html.erb
<h1>Owners#new</h1>
<p>Find me in app/views/owners/new.html.erb</p>

app/views/owners/update.html.erb
<h1>Owners#update</h1>
<p>Find me in app/views/owners/update.html.erb</p>

app/views/reservations/_form.html.erb
<%= form_for([@restaurant, @reservation]) do |f| %>
  <div class="field">
    <%= f.label :time %><br>
    <%= f.datetime_field :time%>
  </div>

  <div class="field">
    <%= f.label :size %>
    <%= f.number_field :size %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reservations/_reservation.html.erb
<%= form_for ([@restaurant, @reservation]) do |f| %>
<% if @reservation.errors.any? %>
<div class="error_explanation">
  <h2>There are <%= pluralize(@reservation.errors.count, "error") %> on this page that prohibited you from making a reservation.</h2>
  <ul>
    <% @reservation.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  </ul>
    <% end %>
</div>
<% end %>
  <div class="field">
    <%= f.label :time %><br>
    <%= f.datetime_select :time, discard_minute: true %>
  </div>

  <div class="field">
    <%= f.label :size %><br>
    <%= f.number_field :size %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reservations/edit.html.erb
<div class="background_reservation_edit">
  <h3 class="edit_heading">Edit Reservation Page</h3>
<%= render 'reservation' %>
</div>

app/views/restaurants/_form.html.erb
<%= form_for @restaurant do |f| %>
  <% if @restaurant.errors.any? %>
  <div class="error_messages">
    <h2>Form is invalid</h2>
      <h4>There are <%= pluralize(@restaurant.errors.count, "errors") %> that prohibited you from creating a restaurant.</h4>
    <ul>
      <% @restaurant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
    <% end %>
  </div>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name%>
  </div>

  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>

  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>

  <div class="field"><br>
    <%= f.label :capacity %><br>
    <%= f.text_field :capacity %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/restaurants/_reservation.html.erb
<%= form_for ([@restaurant, @reservation]) do |f| %>
  <div class="field">
    <%= f.label :time %><br>
    <%= f.datetime_select :time, discard_minute: true %>
  </div>

  <div class="field">
    <%= f.label :size %><br>
    <%= f.number_field :size %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Edit your Restaurant Information</h1>
<%= link_to "Back to all Restaurants", restaurants_path %>
<%= render 'form' %>

app/views/restaurants/index.html.erb
<body class="background">
  <h1 class="headers">Pick a restaurant to make a reservation</h1>


<div class="restaurant_container">
<% @restaurants.each do |restaurant| %>
<div class="restaurant">
  <div class="restaurant_name"> <%= restaurant.name %> </div>
    <ul>
      <li class="restaurant_info"> Address: <%= restaurant.address %></li><br>
      <li class="restaurant_info"> Phone Number: <%=restaurant.phone %></li>
    </ul>
<div class="restaurant_info"><%= link_to "View Restaurant/Book Reservation", restaurant_path(restaurant.id) %></div>
</div>
<% end %>
</div>

<% if current_user %>
  <div class="links"><%= link_to "Create a New Restaurant", new_restaurant_path %></div>
<% end %>

</body>

app/views/restaurants/new.html.erb
<div class="background_new_restaurant">
  <h3 class="create_heading">Create a new Restaurant</h3>
<%= render 'form' %>
</div>

app/views/restaurants/show.html.erb
<div class="restaurant_background">
<div class="back_restaurants">
  <%= link_to "< Back to all Restaurants", restaurants_path %>
</div>
<div class="info">
<h2><%= @restaurant.name %></h2>
<% if current_user && (current_user.id == @restaurant.user_id) && @restaurant.id %>
  <%= link_to "(Edit Restaurant Information)", edit_restaurant_path(@restaurant) %>
<% end %>
<h5>Address: <%= @restaurant.address %></h5>
<h5>Phone Number: <%= @restaurant.phone %></h5>
</div>
<% if current_user %>
    <h3 class="book_reservation_heading">Book a Reservation</h3>
    <%= render 'reservation' %>
  <% else %>
    <p>Please <%= link_to "Log In", new_session_path %> to create a reservation</p>
<% end %>

<h3 class="review_heading">Reviews For <%= @restaurant.name %></h3>

<% @restaurant.reviews.each do |review| %>
  <p class="restaurant_reviews">
    <% if review.user != nil %>
      Comment: <%= review.comment %><br>
    <% end %>
    </p>
<% end %>

<h3 class="write_review">Write a review</h3>
<%= render 'reviews/review' %>
</div>

<h4>Nearby Restaurants</h4>
<% @nearby_restaurants.each do |nearby| %>
  <ol>
    <li>Name: <%= nearby.name %></li>
    <li>Address: <%= nearby.address %></li>
    <li>Distance: <%= nearby.display_distance_to(@restaurant) %> km</li>
  </ol>
<% end %>

app/views/reviews/_review.html.erb
<%= form_for [@restaurant, @review] do |f| %>
  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_field :comment%>
  </div>
  <div class="actions">
    <%= f.submit "Submit", class: "review-submit" %>
  </div>
<% end %>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/destroy.html.erb
<h1>Reviews#destroy</h1>
<p>Find me in app/views/reviews/destroy.html.erb</p>

app/views/reviews/new.html.erb
<h1>Reviews#new</h1>
<p>Find me in app/views/reviews/new.html.erb</p>

app/views/users/new.html.erb
<div class="page-container">
  <div class="page-canvas">
    <div class = "signin-container">
      <h1 class="tagline">Welcome to SeatYourself!</h1>
      <%= form_for @user do |f| %>
        <% if @user.errors.any? %>
          <div class="error_messages">
            <ul>
              <% @user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        <div class="field">

          <%= f.text_field :name, placeholder: "Full name", class: 'fullname-box'%>
        </div>
        <div class="field">

          <%= f.text_field :email, placeholder: "Email", class: 'email-box' %>
        </div>
        <div class="field">

          <%= f.text_field :phone, placeholder: "Phone number", class: 'phone-box' %>
        </div>
        <div class="field">

          <%= f.password_field :password, placeholder: "Password", class: 'password-box' %>
        </div>
        <div class="field">

          <%= f.password_field :password_confirmation, placeholder: "Re-enter password", class: 'password-box' %>
        </div>
        <div class="actions"><%= f.submit 'Create Account', class: 'submit' %></div>
        <% end %>
      </div>
    </div>
  </div>

app/views/users/show.html.erb
<html>
<div class="user-background">

  <div class="greeting">
    Hello, <%= @user.name.capitalize %>!
  </div>

  <div class="back-link">
    <%= link_to "Back to all Restaurants", restaurants_path %>
  </div>

    <div class="reservations">
    <% if @user.reservations != nil %>
    <div class="heading">Your Reservations</div>
        <% @user.reservations.each do |reservation| %>
        <p class="reservation-element">
          <%= reservation.restaurant.name %>
        </p>
          <ul>
            <li class="reservation-item">At: <%= reservation.time %></li>
            <li class="reservation-item">For: <%= reservation.size %> people</li>
          </ul>
          <div class="edit-link">
          <%= link_to "Edit Reservation", edit_restaurant_reservation_path(reservation.restaurant_id, reservation.id) %>
          </div>
      <% end %>
      <% else %>
      <p class="no-reso">
        You have no reservations at this time!
      </p>
    <% end %>
  </div>

  <div class="owned-restaurants">
  <% if @user.owned_restaurants !=nil %>
    <div class="owned-heading">
      Reservations made at Your Restaurant
    </div>
    <% @user.owned_restaurants.each do |owned_restaurant| %>
      <div class="restaurant-name">
        <%= owned_restaurant.name %>
      </div>
        <% owned_restaurant.reservations.each do |reservation| %>
        <p  class="owned-element">
          <ul>
            <li class="owned-reservation-item">At: <%= reservation.time %></li>
            <li class="owned-reservation-item">For: <%= reservation.size %> people</li>
            <li class="owned-reservation-item">Made By: <%= reservation.user.name %></li>
            <li class="owned-reservation-item">Phone: <%= reservation.user.phone %></li>
          </ul>
        </p>
        <% end %>
    <% end %>
  <% else %>
  <p class="no-owner-reso">
    There are no reservations at your restaurant at this time!
  </p>
  <% end %>
</div>

</div>
</html>